
---
- name: Copy dotfiles from repository to home directory
  hosts: localhost
  gather_facts: yes

  vars:
    dirs_to_symlink:
      - nvim
      - scripts
      - sketchybar
      - starship
      - tmux
      - wezterm
      - yabai


  tasks:
    - name: Remove existing .zshrc file
      file:
        path: "{{ ansible_env.HOME }}/.zshrc"
        state: absent
      become: yes

    - name: Create symlink for .zshrc
      file:
        src: "{{ playbook_dir }}/.zshrc"
        dest: "{{ ansible_env.HOME }}/.zshrc"
        state: link
      become: yes

    - name: Remove existing .zsh_profile file
      file:
        path: "{{ ansible_env.HOME }}/.zsh_profile"
        state: absent
      become: yes

    - name: Create symlink for .zsh_profile
      file:
        src: "{{ playbook_dir }}/.zsh_profile"
        dest: "{{ ansible_env.HOME }}/.zsh_profile"
        state: link
      become: yes

    - name: Ensure target directory exists
      file:
        path: "{{ ansible_env.HOME }}/.config"
        state: directory

    - name: Create symbolic links for directories
      file:
        src: "{{ playbook_dir }}/.config/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
        state: link
      with_items: "{{ dirs_to_symlink }}"
