---
- name: Copy dotfiles from repository to home directory
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Copy .zshrc to home directory
      copy:
        src: ".zshrc"
        dest: "{{ ansible_env.HOME }}/.zshrc"
      become: yes

    - name: Copy .zsh_profile to home directory
      copy:
        src: ".zsh_profile"
        dest: "{{ ansible_env.HOME }}/.zsh_profile"
      become: yes


    - name: Create ~/.config directory if it doesn't exist
      file:
        path: "{{ ansible_env.HOME }}/.config"
        state: directory
      become: yes

    - name: Copy .config directory to home directory
      synchronize:
        src: ".config/"
        dest: "{{ ansible_env.HOME }}/.config/"
        mode: pull
      become: yes

