
---
- name: Copy dotfiles from repository to home directory
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Remove existing .zshrc file
      file:
        path: "{{ ansible_env.HOME }}/.zshrc"
        state: absent
      become: yes

    - name: Create symlink for .zshrc
      file:
        src: "{{ playbook_dir }}/.zshrc"
        dest: "{{ ansible_env.HOME }}/.zshrc"
        state: link
      become: yes

    - name: Remove existing .zsh_profile file
      file:
        path: "{{ ansible_env.HOME }}/.zsh_profile"
        state: absent
      become: yes

    - name: Create symlink for .zsh_profile
      file:
        src: "{{ playbook_dir }}/.zsh_profile"
        dest: "{{ ansible_env.HOME }}/.zsh_profile"
        state: link
      become: yes

    - name: Create ~/.config directory if it doesn't exist
      file:
        path: "{{ ansible_env.HOME }}/.config"
        state: directory
      become: yes

    - name: Remove existing files in ~/.config directory from repository
      file:
        path: "{{ ansible_env.HOME }}/.config/{{ item | basename }}"
        state: absent
      with_fileglob:
        - "{{ playbook_dir }}/.config/*"
      become: yes

    - name: Symlink contents of .config to home directory
      file:
        src: "{{ playbook_dir }}/.config/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
        state: link
      with_fileglob:
        - "{{ playbook_dir }}/.config/*"
      become: yes

